2015-12-08 09:33:57,008 - streamparse.storm.component - ERROR - Exception in WordCounter.run()
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/streamparse/storm/component.py", line 487, in run
    self.initialize(storm_conf, context)
  File "bolts/wordcount.py", line 22, in initialize
    COUNT INT      NOT NULL);''')
ProgrammingError: relation "tweetwordcount" already exists

